# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14tC5DEdwza54PLLCdADL4EshhZ7ExAS6
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

data_set=pd.read_csv('/content/heart.csv')
x=data_set[['chol']]
y=data_set['output']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LogisticRegression(max_iter=303)
model.fit(x_train,y_train)
prediction=model.predict(x_test)
plt.scatter(x_test,prediction)
plt.xlabel('cholestrol')
plt.ylabel('output')
print(model.score(x_test,prediction))
a=accuracy_score(x_test,prediction)
print(a)