# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oTuJ72xIa_INLb44816Le71mR_G1DRKe
"""

#Task1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/city_temperature1.csv')
print(df)
at=np.mean(df['AvgTemperature'])
ht=np.max(df['AvgTemperature'])
lt=np.min(df['AvgTemperature'])
threshold=60
thresholds= np.sum(df['AvgTemperature'] > threshold)
print(f'Average Temperature: {at:.2f}°C')
print(f'Highest Temperature: {ht}°C')
print(f'Lowest Temperature: {lt}°C')
print(f'Days Exceeding {threshold}°C: {thresholds}')
plt.plot(df['Day'], df['AvgTemperature'])
plt.xlabel('Day')
plt.ylabel('AvgTemperature (°C)')
plt.title('Daily Temperatures')
plt.show()